// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znegllnnecflwipqxywe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuZWdsbG5uZWNmbHdpcHF4eXdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDM5NTAsImV4cCI6MjA2NTU3OTk1MH0.Wl1uZ4dx3rBZkGtdbORjM1R9OS9_xYIajHClNBjcs8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);